### ISSUE TITLE
Report generator can fail if unexpected condition arose in Selenium Webdriver

### ISSUE THREAD

**Issue by immo-huneke-zuhlke** [allure-framework/mocha-allure-reporter#16]
The generator can throw a number format exception and simply give up when events recorded during the test do not conform to the expected format. The event logs and resulting exception report are attached.

[391793b4-b940-4c4e-b3ff-bc1afc1d3f13-testsuite.xml.txt](https://github.com/allure-framework/mocha-allure-reporter/files/229467/391793b4-b940-4c4e-b3ff-bc1afc1d3f13-testsuite.xml.txt)
[08d1bcf2-3d59-4d1c-b55e-00121cfc2539-testsuite.xml.txt](https://github.com/allure-framework/mocha-allure-reporter/files/229468/08d1bcf2-3d59-4d1c-b55e-00121cfc2539-testsuite.xml.txt)
[20160421_exception.txt](https://github.com/allure-framework/mocha-allure-reporter/files/229469/20160421_exception.txt)

allure-commandline: 1.4.22
mocha-allure-reporter: 1.2.2

**Comment by just-boris** [comment]
Found that failed step has incorrect value in `stop` section.
Fixed that.

**Comment by immo-huneke-zuhlke** [comment]
What a fast response! I tried running the new allure-commandline 1.4.23 on the existing results, but the outcome was the same:
```
$ npm run allure-report

> my-project@0.7.0 allure-report /Users/ihu/Projects/my-project
> allure generate allure-results -o allure-report && allure report open -o allure-report

Exception in thread "main" java.lang.NumberFormatException: For input string: "Error: Error communicating with the remote browser. It may have died. Build info: version: '2.50.0', revision: '1070ace', time: '2016-01-27 18:43:24' System info: host: 'ip-10-0-0-104', ip: '10.0.0.104', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-48-generic', java.version: '1.8.0_72-internal' Driver info: driver.version: FirefoxDriver Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=44.0.2, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}] Session ID: 3432a1c2-b1c8-48aa-9df3-1f9d8eb8dda7"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.sun.xml.internal.bind.DatatypeConverterImpl._parseLong(DatatypeConverterImpl.java:118)
	at ru.yandex.qatools.allure.model.Step_JaxbXducedAccessor_stop.parse(TransducedAccessor_field_Long.java:50)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:195)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:379)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
	at javax.xml.bind.JAXB.unmarshal(JAXB.java:242)
	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:59)
	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:50)
	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:40)
	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:48)
	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:1)
	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.nextSuite(TestCaseReader.java:46)
	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.hasNext(TestCaseReader.java:56)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:61)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
Command aborted due to exception {}.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
```

**Comment by just-boris** [comment]
@immo-huneke-zuhlke run this
```
npm ls | grep allure
```
You should see `allure-js-commons@1.1.5` in the tree. Previous version contain the bug.

**Comment by immo-huneke-zuhlke** [comment]
Thanks - that is the version I have. Any other ideas?

**Comment by just-boris** [comment]
Then I need some code that producing this wrong data.

I suppose that you have something like that 

```js
var myStep = allure.createStep('my step', function() {
   return browser.click('.my-element'); //assume that you have some Selenium Library with promise api.
});

it('is a test case', function() {
    return myStep();
});
```

I tested on this code and it worked. What do you have?

**Comment by immo-huneke-zuhlke** [comment]
I have to be honest with you - I did not fully understand the step creation stuff. I just experimented until I was able to do what I wanted and get out the reports we need.

Because there are already a lot of e2e tests in existence (written with mocha and executed using gulp or a suite executor we've written for use with grunt), one requirement is minimal restructuring. I was able to achieve this by extending our DSL module slightly. In a nutshell, each test script initially calls our bootstrap() function, which injects a "handle" into its callback - an object that can subsequently be queried by the "before" callback to return the initialised Webdriver client. So I added a query to the handle that returns the beforeEach function and another for the afterEach function.

These functions are very simple (all this is done in the context.describe callback):
```
    // initialise allure reporting
    var screenshot;
    var stepCount = 0;

    handle.beforeEachFn = function () {
      if (typeof allure === 'undefined') { // should be global
        return true;
      }
      allure.createStep(reportParams.filename + " '{0}'", function () {
        return ++stepCount;
      });
      screenshot = allure.createStep('save', function (name) {
        return client.screenshot().then(function (res) {
          allure.createAttachment(name, new Buffer(res.value, 'base64'));
        });
      });
      allure.addEnvironment('Browser', browserName);
      _.forEach(reportParams.features, function(feature) {
        allure.feature(feature);
      });
      _.forEach(reportParams.stories, function(story) {
        allure.story(story);
      });
    };

    handle.afterEachFn = function () {
      if (typeof allure === 'undefined') { // should be global
        return true;
      }
      if (this.currentTest.state !== 'passed') {
        return screenshot('screenshot on fail');
      }
    };
```
reportParams is an extra argument that we now pass to the bootstrap function. Thus all I have to do to each of the test scripts is create this structure, add it as a parameter to bootstrap, and then within the "before" callback:
```
    beforeEach(handle.beforeEachFn);
    afterEach(handle.afterEachFn);
```

**Comment by just-boris** [comment]
Checked your code, it works fine for me. There is the gist: https://gist.github.com/just-boris/a33e1453efcaf23c9724c7fdf2072ae2 with my setup, so you can reproduce it.

**Comment by immo-huneke-zuhlke** [comment]
Many thanks for devoting so much time to this. I'll let you know if the problem recurs.

**Comment by immo-huneke-zuhlke** [comment]
In case anyone is following this comment trail, let me add that the problems arose where events were being recorded in the Allure log but not being correctly terminated, so the stop time was not a valid timestamp (either blank or some non-numeric value, such as "true"). This happens if the Allure API is not being used correctly. A few more examples in the documentation would help!
