### ISSUE TITLE
TypeError: test.currentRetry is not a function

### ISSUE THREAD

**Issue by muneermuhammed** [allure-framework/mocha-allure-reporter#22]
I am facing issue when I run my tests with mocha-allure-reporter ,the tests are running successfully with mocha ,but mocha --reporter mocha-allure-reporter returns the following error

> notifications-api@1.0.0 test /app
> mocha --reporter mocha-allure-reporter

2016-11-15T06:13:26.762Z - info: Notification API up and running on port 4000
2016-11-15T06:13:26.773Z - error: Tue, 15 Nov 2016 06:13:26 GMT uncaughtException
2016-11-15T06:13:26.775Z - error: TypeError: test.currentRetry is not a function
at Runner.<anonymous> (/app/node_modules/mocha-allure-reporter/index.js:29:19)
at emitOne (events.js:77:13)
at Runner.emit (events.js:169:7)
at next (/app/node_modules/mocha/lib/runner.js:517:10)
at Runner.runTests (/app/node_modules/mocha/lib/runner.js:556:3)
at /app/node_modules/mocha/lib/runner.js:637:10
at next (/app/node_modules/mocha/lib/runner.js:283:14)
at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:319:5)
at processImmediate [as _immediateCallback] (timers.js:383:17)
npm ERR! Test failed.  See above for more details.
Can anyone help to fix this issue?

**Comment by just-boris** [comment]
The problem was, that we relied on new Mocha API. Even though I added an extra check here, I'd recommend you update your Mocha version to receive all new features.

Eventually, mocha-allure-reporter will stop support Mocha < v3
